# Generated by Django 3.0 on 2019-12-07 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='B_user',
            fields=[
                ('b_uid', models.AutoField(primary_key=True, serialize=False)),
                ('b_username', models.CharField(max_length=32, unique=True, verbose_name='用户名')),
                ('b_password', models.CharField(max_length=16, verbose_name='用户密码')),
                ('b_regdate', models.DateTimeField(auto_now_add=True, verbose_name='注册日期')),
            ],
            options={
                'verbose_name': '用户ID',
                'ordering': ['b_uid'],
            },
        ),
    ]
