# Generated by Django 3.0 on 2019-12-09 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='b_user',
            options={'ordering': ['b_uid'], 'verbose_name': '用户名'},
        ),
        migrations.AddField(
            model_name='b_user',
            name='b_role',
            field=models.CharField(choices=[(1, '摄影师'), (2, 'Coser'), (3, '二次元er')], default=3, max_length=32),
        ),
    ]
