# Generated by Django 3.0.1 on 2019-12-20 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='b_user',
            name='b_user_name',
            field=models.CharField(max_length=32, verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='b_user',
            name='b_user_password',
            field=models.CharField(max_length=255, verbose_name='用户密码'),
        ),
    ]
