# Generated by Django 3.0 on 2019-12-10 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikapi', '0002_auto_20191209_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='b_user',
            name='b_role',
            field=models.CharField(choices=[(1, '摄影师'), (2, 'Coser'), (3, '二次元er')], default='二次元er', max_length=32, verbose_name='角色'),
        ),
    ]
