# Generated by Django 3.0.1 on 2019-12-20 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bikapi', '0002_auto_20191220_0613'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='b_comment',
            options={'ordering': ['b_comment_id'], 'verbose_name': '评论', 'verbose_name_plural': '评论'},
        ),
        migrations.AlterModelOptions(
            name='b_manager',
            options={'ordering': ['b_manage_id'], 'verbose_name': '管理员', 'verbose_name_plural': '管理员'},
        ),
        migrations.AlterModelOptions(
            name='b_section',
            options={'ordering': ['b_section_id'], 'verbose_name': '论坛板块', 'verbose_name_plural': '论坛板块'},
        ),
        migrations.AlterModelOptions(
            name='b_tag',
            options={'ordering': ['b_tag_id'], 'verbose_name': '标签', 'verbose_name_plural': '标签'},
        ),
        migrations.AlterModelOptions(
            name='b_topic',
            options={'ordering': ['b_topic_id'], 'verbose_name': '帖子', 'verbose_name_plural': '帖子'},
        ),
        migrations.AlterModelOptions(
            name='b_zone',
            options={'ordering': ['b_zone_id'], 'verbose_name': '论坛分区', 'verbose_name_plural': '论坛分区'},
        ),
    ]
