# Generated by Django 3.0 on 2019-12-10 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikapi', '0003_auto_20191210_0302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='b_user',
            name='b_role',
            field=models.CharField(choices=[('1', '摄影师'), ('2', 'Coser'), ('3', '二次元er')], default='二次元er', max_length=32, verbose_name='角色'),
        ),
    ]
