# Generated by Django 3.0 on 2019-12-10 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikapi', '0004_auto_20191210_0303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='b_user',
            name='b_username',
            field=models.CharField(max_length=32, verbose_name='用户名'),
        ),
    ]
