# Generated by Django 3.0 on 2019-12-10 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bikapi', '0005_auto_20191210_1334'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='b_user',
            options={'ordering': ['b_uid'], 'verbose_name': '用户名', 'verbose_name_plural': '用户名'},
        ),
    ]
