# Generated by Django 3.0.1 on 2019-12-26 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikapi', '0005_auto_20191220_0848'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='b_user',
            options={'ordering': ['b_user_id'], 'verbose_name': '用户名', 'verbose_name_plural': '用户'},
        ),
        migrations.RemoveField(
            model_name='b_comment',
            name='b_comment_parent',
        ),
        migrations.AlterField(
            model_name='b_section',
            name='b_section_count',
            field=models.IntegerField(default=0, verbose_name='板块主题数'),
        ),
        migrations.AlterField(
            model_name='b_section',
            name='b_section_num',
            field=models.IntegerField(default=0, verbose_name='板块点击次数'),
        ),
        migrations.AlterField(
            model_name='b_topic',
            name='b_topic_click_num',
            field=models.IntegerField(default=0, verbose_name='帖子点击次数'),
        ),
        migrations.AlterField(
            model_name='b_topic',
            name='b_topic_comment_num',
            field=models.IntegerField(default=0, verbose_name='帖子评论次数'),
        ),
        migrations.AlterField(
            model_name='b_topic',
            name='b_topic_down_num',
            field=models.IntegerField(default=0, verbose_name='点踩数'),
        ),
        migrations.AlterField(
            model_name='b_topic',
            name='b_topic_up_num',
            field=models.IntegerField(default=0, verbose_name='点赞数'),
        ),
    ]
