# Generated by Django 3.0.1 on 2019-12-27 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikapi', '0007_b_topic_b_topic_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='b_topic',
            name='b_topic_file',
            field=models.FileField(blank=True, upload_to='images', verbose_name='附件'),
        ),
    ]
