# Generated by Django 3.0 on 2019-12-17 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bikapi', '0016_auto_20191217_0715'),
    ]

    operations = [
        migrations.AddField(
            model_name='b_user',
            name='b_phone',
            field=models.CharField(blank=True, default='', max_length=16, verbose_name='手机号码'),
        ),
        migrations.AddField(
            model_name='b_user',
            name='email',
            field=models.EmailField(default='2019-12-17', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='b_comment',
            name='b_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bikapi.B_User'),
        ),
        migrations.AlterField(
            model_name='b_section',
            name='b_section_uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bikapi.B_User'),
        ),
        migrations.AlterField(
            model_name='b_topic',
            name='b_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bikapi.B_User'),
        ),
        migrations.AlterField(
            model_name='b_up',
            name='b_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bikapi.B_User'),
        ),
    ]
