# Generated by Django 3.0 on 2019-12-17 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bikapi', '0017_auto_20191217_0723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='b_comment',
            name='b_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bikapi.B_User'),
        ),
        migrations.AlterField(
            model_name='b_section',
            name='b_section_uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bikapi.B_User'),
        ),
        migrations.AlterField(
            model_name='b_topic',
            name='b_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bikapi.B_User'),
        ),
        migrations.AlterField(
            model_name='b_up',
            name='b_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bikapi.B_User'),
        ),
        migrations.AlterField(
            model_name='b_user',
            name='b_sex',
            field=models.CharField(choices=[('1', '男'), ('2', '女'), ('3', '未选择')], default='3', max_length=32, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='b_user',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True),
        ),
    ]
