# Generated by Django 3.0 on 2019-12-17 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bikapi', '0019_auto_20191217_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='b_comment',
            name='b_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bikapi.B_User'),
        ),
        migrations.AlterField(
            model_name='b_section',
            name='b_section_uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bikapi.B_User'),
        ),
        migrations.AlterField(
            model_name='b_topic',
            name='b_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bikapi.B_User'),
        ),
        migrations.AlterField(
            model_name='b_up',
            name='b_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bikapi.B_User'),
        ),
        migrations.AlterField(
            model_name='b_user',
            name='b_role',
            field=models.CharField(choices=[('1', '摄影师'), ('2', 'Coser'), ('3', '二次元er')], default='3', max_length=32, verbose_name='角色'),
        ),
        migrations.AlterField(
            model_name='b_user',
            name='b_sex',
            field=models.CharField(choices=[('1', '未选择'), ('2', '男'), ('3', '女')], default='1', max_length=32, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='b_user',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, unique=True),
        ),
    ]
