# Generated by Django 3.0 on 2019-12-17 08:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bikapi', '0026_auto_20191217_0757'),
    ]

    operations = [
        migrations.AddField(
            model_name='b_user',
            name='b_avatar',
            field=models.FileField(blank=True, upload_to='static/images/', verbose_name='头像'),
        ),
        migrations.AddField(
            model_name='b_user',
            name='b_birthday',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='生日'),
        ),
        migrations.AddField(
            model_name='b_user',
            name='b_phone',
            field=models.CharField(blank=True, default='', max_length=16, verbose_name='手机号码'),
        ),
        migrations.AddField(
            model_name='b_user',
            name='b_sex',
            field=models.CharField(choices=[('1', '未选择'), ('2', '男'), ('3', '女')], default='1', max_length=32, verbose_name='性别'),
        ),
        migrations.AddField(
            model_name='b_user',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='b_comment',
            name='b_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bikapi.B_User'),
        ),
        migrations.AlterField(
            model_name='b_section',
            name='b_section_uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bikapi.B_User'),
        ),
        migrations.AlterField(
            model_name='b_topic',
            name='b_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bikapi.B_User'),
        ),
        migrations.AlterField(
            model_name='b_up',
            name='b_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bikapi.B_User'),
        ),
    ]
