# Generated by Django 3.0 on 2019-12-17 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bikapi', '0031_auto_20191217_0840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='b_comment',
            name='b_parent',
        ),
        migrations.RemoveField(
            model_name='b_comment',
            name='b_topic',
        ),
        migrations.RemoveField(
            model_name='b_comment',
            name='b_user',
        ),
        migrations.DeleteModel(
            name='B_Integral',
        ),
        migrations.DeleteModel(
            name='B_Manager',
        ),
        migrations.RemoveField(
            model_name='b_section',
            name='b_section_uid',
        ),
        migrations.RemoveField(
            model_name='b_section',
            name='b_zone',
        ),
        migrations.RemoveField(
            model_name='b_topic',
            name='b_section',
        ),
        migrations.RemoveField(
            model_name='b_topic',
            name='b_tag',
        ),
        migrations.RemoveField(
            model_name='b_topic',
            name='b_user',
        ),
        migrations.RemoveField(
            model_name='b_topic2tag',
            name='b_tag',
        ),
        migrations.RemoveField(
            model_name='b_topic2tag',
            name='b_topic',
        ),
        migrations.RemoveField(
            model_name='b_up',
            name='b_topic',
        ),
        migrations.RemoveField(
            model_name='b_up',
            name='b_user',
        ),
        migrations.RemoveField(
            model_name='b_user',
            name='b_avatar',
        ),
        migrations.RemoveField(
            model_name='b_user',
            name='b_birthday',
        ),
        migrations.RemoveField(
            model_name='b_user',
            name='b_phone',
        ),
        migrations.RemoveField(
            model_name='b_user',
            name='b_sex',
        ),
        migrations.RemoveField(
            model_name='b_user',
            name='email',
        ),
        migrations.DeleteModel(
            name='B_Comment',
        ),
        migrations.DeleteModel(
            name='B_Section',
        ),
        migrations.DeleteModel(
            name='B_Tag',
        ),
        migrations.DeleteModel(
            name='B_Topic',
        ),
        migrations.DeleteModel(
            name='B_Topic2Tag',
        ),
        migrations.DeleteModel(
            name='B_Up',
        ),
        migrations.DeleteModel(
            name='B_Zone',
        ),
    ]
