# Generated by Django 3.0 on 2019-12-17 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bikapi', '0035_auto_20191217_0904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='b_comment',
            name='b_comment_parent',
        ),
        migrations.RemoveField(
            model_name='b_comment',
            name='b_comment_topic',
        ),
        migrations.RemoveField(
            model_name='b_comment',
            name='b_comment_user',
        ),
        migrations.DeleteModel(
            name='B_Integral',
        ),
        migrations.DeleteModel(
            name='B_Manager',
        ),
        migrations.RemoveField(
            model_name='b_section',
            name='b_section_uid',
        ),
        migrations.RemoveField(
            model_name='b_section',
            name='b_section_zone',
        ),
        migrations.RemoveField(
            model_name='b_topic',
            name='b_topic_section',
        ),
        migrations.RemoveField(
            model_name='b_topic',
            name='b_topic_tag',
        ),
        migrations.RemoveField(
            model_name='b_topic',
            name='b_topic_tuser',
        ),
        migrations.RemoveField(
            model_name='b_topic2tag',
            name='b_t2t_tag',
        ),
        migrations.RemoveField(
            model_name='b_topic2tag',
            name='b_t2t_topic',
        ),
        migrations.RemoveField(
            model_name='b_up',
            name='b_up_topic',
        ),
        migrations.RemoveField(
            model_name='b_up',
            name='b_up_user',
        ),
        migrations.RemoveField(
            model_name='b_user',
            name='b_user_avatar',
        ),
        migrations.RemoveField(
            model_name='b_user',
            name='b_user_birthday',
        ),
        migrations.RemoveField(
            model_name='b_user',
            name='b_user_email',
        ),
        migrations.RemoveField(
            model_name='b_user',
            name='b_user_phone',
        ),
        migrations.RemoveField(
            model_name='b_user',
            name='b_user_regdate',
        ),
        migrations.RemoveField(
            model_name='b_user',
            name='b_user_role',
        ),
        migrations.RemoveField(
            model_name='b_user',
            name='b_user_sex',
        ),
        migrations.DeleteModel(
            name='B_Comment',
        ),
        migrations.DeleteModel(
            name='B_Section',
        ),
        migrations.DeleteModel(
            name='B_Tag',
        ),
        migrations.DeleteModel(
            name='B_Topic',
        ),
        migrations.DeleteModel(
            name='B_Topic2Tag',
        ),
        migrations.DeleteModel(
            name='B_Up',
        ),
        migrations.DeleteModel(
            name='B_Zone',
        ),
    ]
