# Generated by Django 3.0 on 2019-12-17 09:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bikapi', '0036_auto_20191217_0915'),
    ]

    operations = [
        migrations.CreateModel(
            name='B_Integral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_integral_num', models.IntegerField(default=-20)),
            ],
        ),
        migrations.CreateModel(
            name='B_Manager',
            fields=[
                ('b_manage_id', models.AutoField(primary_key=True, serialize=False)),
                ('b_manage_name', models.CharField(max_length=32, verbose_name='管理员')),
                ('b_manage_password', models.CharField(max_length=16, verbose_name='管理员密码')),
            ],
        ),
        migrations.CreateModel(
            name='B_Section',
            fields=[
                ('b_section_id', models.AutoField(primary_key=True, serialize=False)),
                ('b_section_name', models.CharField(max_length=64)),
                ('b_section_explanation', models.CharField(max_length=255)),
                ('b_section_num', models.IntegerField()),
                ('b_section_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='B_Tag',
            fields=[
                ('b_tag_id', models.AutoField(primary_key=True, serialize=False)),
                ('b_tag_name', models.CharField(max_length=32, verbose_name='标签名')),
            ],
        ),
        migrations.CreateModel(
            name='B_Topic',
            fields=[
                ('b_topic_id', models.AutoField(primary_key=True, serialize=False)),
                ('b_topic_title', models.CharField(blank=True, max_length=64, verbose_name='标题')),
                ('b_topic_desc', models.CharField(max_length=255, verbose_name='摘要')),
                ('b_topic_content', models.TextField(verbose_name='帖子内容')),
                ('b_topic_createtime', models.DateTimeField(auto_now_add=True, verbose_name='发帖时间')),
                ('b_topic_click_num', models.IntegerField(verbose_name='帖子点击次数')),
                ('b_topic_comment_num', models.IntegerField(verbose_name='帖子评论次数')),
                ('b_topic_up_num', models.IntegerField(verbose_name='点赞数')),
                ('b_topic_down_num', models.IntegerField(verbose_name='点赞数')),
                ('b_topic_section', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bikapi.B_Section')),
            ],
        ),
        migrations.CreateModel(
            name='B_Zone',
            fields=[
                ('b_zone_id', models.AutoField(primary_key=True, serialize=False)),
                ('b_zone_name', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='b_user',
            name='b_user_avatar',
            field=models.FileField(blank=True, upload_to='static/images/', verbose_name='头像'),
        ),
        migrations.AddField(
            model_name='b_user',
            name='b_user_birthday',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='生日'),
        ),
        migrations.AddField(
            model_name='b_user',
            name='b_user_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='b_user',
            name='b_user_phone',
            field=models.CharField(blank=True, default='', max_length=16, verbose_name='手机号码'),
        ),
        migrations.AddField(
            model_name='b_user',
            name='b_user_regdate',
            field=models.DateTimeField(auto_now_add=True, default='2019-12-12', verbose_name='注册日期'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='b_user',
            name='b_user_role',
            field=models.CharField(choices=[('1', '摄影师'), ('2', 'Coser'), ('3', '二次元er')], default='3', max_length=32, verbose_name='角色'),
        ),
        migrations.AddField(
            model_name='b_user',
            name='b_user_sex',
            field=models.CharField(choices=[('1', '未选择'), ('2', '男'), ('3', '女')], default='1', max_length=32, verbose_name='性别'),
        ),
        migrations.CreateModel(
            name='B_Up',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_is_up', models.BooleanField()),
                ('b_up_topic', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bikapi.B_Topic')),
                ('b_up_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bikapi.B_User')),
            ],
        ),
        migrations.CreateModel(
            name='B_Topic2Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_t2t_tag', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bikapi.B_Tag')),
                ('b_t2t_topic', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bikapi.B_Topic')),
            ],
        ),
        migrations.AddField(
            model_name='b_topic',
            name='b_topic_tag',
            field=models.ManyToManyField(through='bikapi.B_Topic2Tag', to='bikapi.B_Tag'),
        ),
        migrations.AddField(
            model_name='b_topic',
            name='b_topic_tuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bikapi.B_User'),
        ),
        migrations.AddField(
            model_name='b_section',
            name='b_section_uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bikapi.B_User'),
        ),
        migrations.AddField(
            model_name='b_section',
            name='b_section_zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bikapi.B_Zone'),
        ),
        migrations.CreateModel(
            name='B_Comment',
            fields=[
                ('b_comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('b_comment_content', models.CharField(max_length=255)),
                ('b_comment_create_time', models.DateTimeField(auto_now_add=True)),
                ('b_comment_parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bikapi.B_Comment')),
                ('b_comment_topic', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bikapi.B_Topic')),
                ('b_comment_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bikapi.B_User')),
            ],
        ),
    ]
